auto: true

#markdown: rdiscount
highlighter: 'pygments'
#paginate: 8
permalink: /:title

title: ŞÈ½£ÌıÓê
url: http://jh-tingyu.github.io
feed: /atom.xml
author_info: <a href="http://jh-tingyu.github.io/">ŞÈ½£ÌıÓê</a>
