auto: true

markdown: rdiscount

highlighter: 'pygments'
#paginate: 8
permalink: /:title

name: “奕剑听雨”
title: 奕剑听雨
description: Everything about Mukosame.
url: http://jh-tingyu.github.io
feed: /atom.xml
author_info: <a href="http://jh-tingyu.github.io/">Mukosame</a>
