encoding: UTF-8
# Site settings

title: 奕剑听雨
email: 1464921184@qq.com
description: > # this means to ignore newlines until "baseurl:"
  个人博客
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jh-tingyu.github.io/" # the base hostname & protocol for your site
#twitter_username: test 
github_username:  jh-tingyu 
disqus: hueidou

# Build settings
markdown: rdiscount

permalink: /:year/:month/:day/:title.html